logging:
  level:
    orgspringframework:
      web:
        filter:
          CommonsRequestLoggingFilter: DEBUG

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trainingsplanerTest
    username: Zazzzzzels
    password: makeSoftware21
  jpa:
    hibernate:
      ddl-auto: create

springdoc:
  api-docs:
    path: /resource-server/tp-resource-server-api-docs
  swagger-ui:
    path: /resource-server/swagger-ui.html
