app:
  authServer:
    tokenValidationEndpoint: http://localhost:8082/check/token

server:
  port: 8081
  error:
    include-stacktrace: never

logging:
  level:
    de.tlg.trainingsplaner.resourceserver: DEBUG
    orgspringframework.web.filter.CommonsRequestLoggingFilter: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trainingsplanerTest
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

springdoc:
  api-docs:
    path: /resource-server/tp-resource-server-api-docs
  swagger-ui:
    path: /resource-server/swagger-ui.html
